- include_tasks: bash.yml
- include_tasks: vim.yml
- include_tasks: git.yml
- include_tasks: sssd.yml
- include_tasks: httpd.yml
- include_tasks: php.yml
- include_tasks: workspace.yml
- include_tasks: vagrant.yml
