- name: Setup NetworkManager VPN connection
  become: True
  copy:
    src: '{{ SECRETS_PATH }}/BRQ.ovpn'
    dest: /etc/NetworkManager/system-connections/BRQ.ovpn
    owner: root
    group: root
    mode: 0600
    force: yes
  register: result

- name: Restart NetworkManager
  become: True
  service:
    name: NetworkManager.service
    enabled: yes
    state: restarted
  when: result.changed

- name: Wait for a VPN access
  pause:
    prompt: Please, connect to VPN and press ENTER.
