.de FN
\fI\|\\$1\|\fP
..
.TH AUTHCONFIG 8 "Mon 30 July 2001" "Red Hat, Inc."
.UC 4
.SH NAME
authconfig \- an interface for configuring system authentication resources
.SH SYNOPSIS
\fBauthconfig\fR [--back] [--test] [--nostart] [--kickstart] [--probe]
[--enablecache] [--disablecache]
[--enablenis [--nisdomain <domain>] [--nisserver <nisserver[,nisserver...]>] ]
[--disablenis]
[--enableshadow] [--disableshadow]
[--enablemd5] ] [--disablemd5] ]
[--enableldap [--enableldapauth] [--enableldapssl]
[--ldapserver <ldapserver>] [--ldapbasedn <basedn>] ]
[--disableldap] [--disableldapauth]
[--enablekrb5 [ --krb5realm <realm> ] [--krb5kdc <hostname[,hostname,...]>]
[--disablekrb5]
[--krb5adminserver <hostname[,hostname,...]>] ]
[--enablehesiod [--hesiodlhs <lhs>] [--hesiodrhs <rhs>] ] [--disablehesiod]
[--enablesmb [--smbworkgroup <workgroup>] [--smbservers <server[,server]>]]
.SH DESCRIPTION
\fBauthconfig\fR provides a simple method of configuring
/etc/sysconfig/network to handle NIS, as well as /etc/passwd and
/etc/shadow, the files used for shadow password support.  Basic LDAP,
Kerberos 5, and SMB (authentication) client configuration is also provided.

The authconfig window contains a \fBCancel\fR button by default. If
\fB--back\fR is specified at run time, a \fBBack\fR button is presented
instead. If \fB--test\fR is specified, \fBauthconfig\fR can be run by
users other then root, and any configuration changes are not saved. If
\fB--nostart\fR is specified (which is what the install program does),
ypbind will not be started or stopped immediately following program
execution, but only enabled to start or stop at boot time. if
\fB--kickstart\fR is specified, no interactive screens will be seen.
The values the program will use will be those specified by the other
options (\fB--enablemd5\fR, \fB--usehadow\fR, etc.).

The \fB--enablenis\fP, \fB--enableldap\fP, and \fB--enablehesiod\fP options
are used to configure user information services in \fB/etc/nsswitch.conf\fP,
the \fB--enablecache\fP option is used to configure naming services caching,
and the \fB--enableshadow\fP, \fB--enablemd5\fP, \fB--enableldapauth\fP,
\fB--enablekrb5\fP and \fB--enablesmb\fP options are used to configure
authentication functions via \fB/etc/pam.d/system-auth\fP.  Each
\fB--enable\fP has a matching \fB--disable\fP option that disables the service
if it is already enabled.

The \fB--probe\fP flag instructs \fBauthconfig\fP to use DNS and other means
to guess at configuration information for the current host, print its guesses
to standard output, and exit.

The default in kickstart mode (i.e. without any additional options) is to
not change the current settings.

.PD
.SH "RETURN CODES"
\fBauthconfig\fR returns 0 on success, 2 on error, and 1 if the user cancelled
the program (by using either the \fBCancel\fR or \fBBack\fR button).

.PD
.SH FILES
.PD 0
.TP
.TP
.FN /etc/sysconfig/authconfig
Used to track whether or not particular authentication mechanisms are enabled.
Currently includes variables named USESHADOW, USEMD5, USEKERBEROS, USELDAPAUTH,
USESMBAUTH, USEHESIOD, USENIS.
.TP
.FN /etc/passwd, /etc/shadow
Used for shadow password support.
.TP
.FN /etc/yp.conf
Configuration file for NIS support.
.TP
.FN /etc/sysconfig/network
Another configuration file for NIS support.
.TP
.FN /etc/ldap.conf
.FN /etc/openldap/ldap.conf
Used to configure LDAP (and OpenLDAP).
.TP
.FN /etc/krb5.conf
Used to configure Kerberos 5.
.TP
.FN /etc/krb.conf
Used to configure Kerberos IV (write-only).
.TP
.FN /etc/hesiod.conf
Used to configure Hesiod.
.TP
.FN /etc/pam_smb.conf
Used to configure SMB authentication.
.TP
.TP
.FN /etc/nsswitch.conf
Used to configure user information services.
.TP
.FN /etc/pam.d/system-auth
Used to configure PAM for system services via pam_stack(8).

.PD
.SH "SEE ALSO"
passwd(5), shadow(5), pwconv(1), domainname(1), ypbind(8), nsswitch.conf(5)

.SH AUTHORS
.nf
Nalin Dahyabhai <nalin@redhat.com>, Preston Brown <pbrown@redhat.com>, Matt Wilson <msw@redhat.com>
.fi
