.de FN
\fI\|\\$1\|\fP
..
.TH AUTHCONFIG-GTK 8 "31 March 2010" "Red Hat, Inc."
.SH NAME
authconfig-gtk, system-config-authentication \- GUI utility for configuring user identity and
system authentication services
.SH SYNOPSIS
\fBauthconfig-gtk\fR [--nox] [--updateall] [--firstboot]
.SH DESCRIPTION
\fBauthconfig-gtk\fR provides a simple graphical user interface for configuring
user identity and system authentication services.
It provides basic configuration options to handle NIS, LDAP, Kerberos 5,
and Winbind client configuration.

.PD
.SH OPTIONS
If the \fB--nox\fR option is specified, \fBauthconfig\fR command line utility
is run instead of the GUI.

The \fB--updateall\fR option forces overwriting of all configuration files not
only the files affected by the changes made in the user interaction with the GUI.
This option can be useful in case the configuration files are broken by manual
editing.

The \fB--firstboot\fR option is to be used only when \fIfirstboot\fP utility
runs the GUI during the first setup of the system after installation.

.PD
.SH "RETURN CODES"
\fBauthconfig-gtk\fR returns 0 on success, non zero on error.

.PD
.SH "SEE ALSO"
authconfig(8), system-auth-ac(5)

.SH AUTHORS
.nf
Nalin Dahyabhai <nalin@redhat.com>, Preston Brown <pbrown@redhat.com>,
Matt Wilson <msw@redhat.com>, Tomas Mraz <tmraz@redhat.com>
.fi
