- name: Add servers to global known hosts file
  become: True
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: '{{ item }}'
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa {{ item }}') }}"
  with_items:
  - pkgs.fedoraproject.org
  - fedorapeople.org
  - github.com
  - pagure.io
  - '{{ INTERNAL_KNOWN_HOSTS }}'

- name: 'Create SSH directories'
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - '{{ HOME }}/.ssh'

- name: Copy SSH keys
  copy:
    src: '{{ SECRETS }}/certificates/ssh/{{ item }}'
    dest: '{{ HOME }}/.ssh/{{ item }}'
    owner: '{{ USER }}'
    group: '{{ USER }}'
    mode: 0600
  with_items:
  - id_rsa
  - id_rsa.pub

- name: Create SSH config
  template:
    src: user_config
    dest: '{{ HOME }}/.ssh/config'
    mode: a=,u=rw
