- name: 'Create libvirt polkit rule'
  become: True
  template:
    src: libvirt.polkit
    dest: '/etc/polkit-1/rules.d/00-org.libvirt.unix.manager.rules'
    mode: a=r,u=rw

- name: 'Create {{ LIBVIRT_STORAGE }} directory'
  become: True
  file:
    path: '{{ LIBVIRT_STORAGE }}'
    state: directory
    owner: qemu
    group: qemu
    mode: a=rwx

- name: 'Start libvirt service'
  become: True
  service:
    name: libvirtd.service
    enabled: yes
    state: started

- name: 'Create libvirt default pool at {{ LIBVIRT_STORAGE }}'
  become: True
  shell: |
    virsh pool-dumpxml default | grep "{{ LIBVIRT_STORAGE }}"
    if [ $? -eq 0 ]; then
      echo "Pool default in {{ LIBVIRT_STORAGE }} already exists. Nothing to do."
      exit 255
    fi
    
    virsh pool-destroy default
    virsh pool-undefine default
    virsh pool-define-as --name default --type dir --target "{{ LIBVIRT_STORAGE }}"
    virsh pool-autostart default
    virsh pool-start default
  register: result
  failed_when: "result.rc != 255 and result.rc != 0"
  changed_when: "result.rc == 0"
