- name: 'Create directories'
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - '{{ HOME }}/.mozilla'
  - '{{ HOME }}/.mozilla/firefox'
  - '{{ HOME }}/.thunderbird'

- name: Check if Firefox profile "{{ FIREFOX_PROFILE }}" exists
  stat:
    path: '{{ HOME }}/.mozilla/firefox/{{ FIREFOX_PROFILE }}/'
  register: profile

- name: 'Copy Firefox profile'
  synchronize:
    src: 'firefox-profile/'
    dest: '{{ HOME }}/.mozilla/firefox/{{ FIREFOX_PROFILE }}/'
  when: not profile.stat.exists

- name: 'Initialize Firefox profile'
  template:
    src: firefox-profile.ini
    dest: '{{ HOME }}/.mozilla/firefox/profiles.ini'
    mode: a=,u=rw

- name: Import certificates to firefox
  become: True
  shell: |
    /usr/bin/certutil -L -d "{{ HOME }}/.mozilla/firefox/{{ FIREFOX_PROFILE }}" | grep "{{ item.name }}"
    if [ $? -eq 0 ]; then
      echo "Certificate {{ item.name }} already exists. Nothing to do."
      exit 255
    fi

    /usr/bin/pk12util \
      -i "{{ item.path }}" \
      -d "{{ HOME }}/.mozilla/firefox/{{ FIREFOX_PROFILE }}" \
      -W "{{ item.password }}"
  register: result
  failed_when: "result.rc != 255 and result.rc != 0"
  changed_when: "result.rc == 0"
  with_items:
  - { name: '{{ USER }} - Fedora Project', password: '{{ FAS_PASSWORD }}', path: '{{ SECRETS }}/certificates/fedora/fedora-browser-cert.p12' }

- name: Attention!
  debug:
    msg: "Do not forget to set Firefox master password and activate synchronization."
  when: not profile.stat.exists

- name: Check if Thunderbird profile "{{ THUNDERBIRD_PROFILE }}" exists
  stat:
    path: '{{ HOME }}/.thunderbird/{{ THUNDERBIRD_PROFILE }}/'
  register: profile

- name: 'Copy Thunderbird profile'
  synchronize:
    src: '{{ SECRETS }}/configs/thunderbird-profile/'
    dest: '{{ HOME }}/.thunderbird/{{ THUNDERBIRD_PROFILE }}/'
  when: not profile.stat.exists

- name: 'Initialize Thunderbird profile'
  template:
    src: thunderbird-profile.ini
    dest: '{{ HOME }}/.thunderbird/profiles.ini'
    mode: a=,u=rw
