---
- hosts: all
  roles:
  - nvidia
  - packages
  - selinux
  - google-drive
  - fetch-internals
  vars_files:
  - variables.yml

- hosts: all
  roles:
  - internals
  - ssh-client
  - developer-machine
  - eclipse
  - applications
  - cinnamon
  - clean-artifacts
  vars_files:
  - variables.yml
  - '{{ SECRETS_VARS }}'
