- name: Check if the system have NVIDIA VGA
  become: True
  shell: |
    /sbin/lspci | grep VGA | grep -i NVIDIA
  register: vga_result
  failed_when: "vga_result.rc != 0 and vga_result.rc != 1"
  changed_when: False

- name: 'NVIDIA VGA found: nvidia_vga=True'
  set_fact:
    nvidia_vga=True
  when: vga_result.rc == 0

- name: 'NVIDIA VGA not found: nvidia_vga=False'
  set_fact:
    nvidia_vga=False
  when: vga_result.rc != 0
