- name: Install certificates
  become: True
  shell: |
    rpm --import "{{ item }}"
  args:
    warn: false
  with_items:
  - https://packages.microsoft.com/keys/microsoft.asc

- name: Install RPM Fusion repositories
  become: True
  dnf:
    state: present
    name:
    - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm'
    - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm'

- name: Install NVIDIA drivers
  become: True
  package:
    name: '{{ item }}'
    state: present
  when: nvidia_vga == True
  with_items:
  - akmod-nvidia
  - libva-utils
  - libva-vdpau-driver
  - vdpauinfo
  - xorg-x11-drv-nvidia
  - xorg-x11-drv-nvidia-cuda
  - xorg-x11-drv-nvidia-cuda-libs

- name: Install additional repositories
  become: True
  template:
    src: repo
    dest: '/etc/yum.repos.d/{{ item.name }}.repo'
    owner: root
    group: root
    mode: 0644
  with_items:
  - {name: 'visual-studio-code', url: 'https://packages.microsoft.com/yumrepos/vscode'}

- name: Install additional copr repositories
  become: True
  shell: |
    dnf copr enable -y "{{ item }}"
  args:
    warn: false
  with_items:
  - sergiomb/google-drive-ocamlfuse

- name: Install packages
  become: True
  dnf:
    state: present
    name:
    - abrt
    - adcli
    - aircrack-ng
    - ansible
    - asciidoc
    - augeas-devel
    - authselect
    - autoconf
    - automake
    - awscli
    - bash-completion
    - bc
    - bind-utils
    - c-ares-devel
    - check
    - check-devel
    - cifs-utils-devel
    - cinnamon
    - clang
    - code
    - cryptsetup
    - cups
    - curl
    - d-feet
    - dbus-devel
    - dbus-libs
    - diffstat
    - dnsmasq
    - docbook-style-xsl
    - doxygen
    - eclipse-cdt
    - eclipse-changelog
    - eclipse-dltk-ruby
    - eclipse-dltk-sh
    - eclipse-egit
    - eclipse-linuxtools
    - eclipse-manpage
    - eclipse-mpc
    - eclipse-pydev
    - eclipse-rpm-editor
    - fakeroot
    - fedora-packager
    - fedpkg
    - filezilla
    - findutils
    - firefox
    - firewalld
    - freeipa-client
    - gcc
    - gdb
    - gdm-pam-extensions-devel
    - gettext
    - gettext-devel
    - gimp
    - git
    - glib2-devel
    - gnutls-utils
    - google-drive-ocamlfuse
    - hexchat
    - http-parser-devel
    - httpd
    - hub
    - ImageMagick
    - jansson-devel
    - java
    - keepass
    - keyutils-libs-devel
    - koji
    - krb5-devel
    - krb5-server
    - ldb-tools
    - libcap
    - libcap-ng
    - libcmocka
    - libcmocka-devel
    - libcollection-devel
    - libcurl-devel
    - libdhash-devel
    - libini_config-devel
    - libldb
    - libldb-devel
    - libnfsidmap-devel
    - libnl3-devel
    - libpath_utils-devel
    - libref_array-devel
    - libreoffice
    - libselinux-devel
    - libselinux-python
    - libselinux-python3
    - libsemanage-devel
    - libsmbclient-devel
    - libtalloc
    - libtalloc-devel
    - libtdb
    - libtdb-devel
    - libtevent
    - libtevent-devel
    - libtool
    - libuuid-devel
    - libvirt
    - libvirt-daemon-kvm
    - libvirt-devel
    - libxml2
    - libxslt
    - m4
    - mariadb
    - mariadb-server
    - meld
    - NetworkManager
    - NetworkManager-ppp
    - nodejs
    - npm
    - nspr-devel
    - nss-devel
    - nss-tools
    - nss-util-devel
    - nss_wrapper
    - oddjob
    - oddjob-mkhomedir
    - openldap-clients
    - openldap-devel
    - openldap-servers
    - openssh
    - openssl
    - openssl-devel
    - openvpn
    - p11-kit-devel
    - pam-devel
    - pam_wrapper
    - pcre-devel
    - php
    - php-common
    - php-mysqlnd
    - phpmyadmin
    - phpunit7
    - pkgconfig
    - po4a
    - popt-devel
    - python2
    - python2-dbus
    - python2-devel
    - python2-ldap
    - python2-ldb
    - python2-pep8
    - python2-psutil
    - python2-pytest
    - python2-requests
    - python2-winrm
    - python3
    - python3-clint
    - python3-dbus
    - python3-devel
    - python3-dnf
    - python3-ldap
    - python3-ldb
    - python3-psutil
    - python3-pytest
    - python3-requests
    - python3-winrm
    - qemu-kvm
    - rdesktop
    - realmd
    - resolv_wrapper
    - ruby-devel
    - rubygem-ruby-libvirt
    - samba-common-tools
    - samba-devel
    - samba-winbind
    - samba4-devel
    - selinux-policy-targeted
    - socket_wrapper
    - softhsm >= 2.1.0
    - sssd
    - sssd-*
    - systemd
    - systemd-devel
    - systemtap-sdt-devel
    - testdisk
    - thunderbird
    - tig
    - uid_wrapper
    - vagrant
    - vagrant-libvirt
    - vagrant-sshfs
    - valgrind
    - vim
    - vim-common
    - vim-enhanced
    - virt-manager
    - wget
    - wireshark
    - xclip
    - zanata-client

- name: Install debug information for specific packages
  become: True
  dnf:
    state: present
    enablerepo: '*-debuginfo'
    name:
    - authselect-debuginfo
    - authselect-libs-debuginfo
    - dbus-debuginfo
    - ding-libs-debuginfo
    - glibc-debuginfo
    - libcmocka-debuginfo
    - libdhash-debuginfo
    - libini_config-debuginfo
    - libldb-debuginfo
    - libtalloc-debuginfo
    - libtevent-debuginfo
