- name: Upgrade all packages to their latest version
  become: True
  package:
    name: '*'
    state: latest

- name: 'Include distribution specific package tasks [{{ ansible_distribution }} {{ ansible_distribution_major_version }}]'
  include_tasks: '{{ include_file }}'
  loop_control:
    loop_var: include_file
  with_first_found:
    - files:
        - '{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
