- name: Find GCC include directory
  set_fact:
    gcc_include_dir="{{ lookup('pipe', '/bin/bash -c \"ls -d /usr/lib/gcc/x86_64-redhat-linux/* | tail -n 1\"') }}/include"

- name: Set Fedora 25 specific facts
  set_fact:
    ECLIPSE_RELEASE="neon"
  when: ansible_distribution == 'Fedora' and ansible_distribution_version == '25'

- name: Set Fedora 26+ specific facts
  set_fact:
    ECLIPSE_RELEASE="oxygen"
  when: ansible_distribution == 'Fedora' and ansible_distribution_version >= '26'

- name: Install eclipse packages
  become: True
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - eclipse-cdt
  - eclipse-changelog
  - eclipse-dltk-ruby
  - eclipse-dltk-sh
  - eclipse-egit
  - eclipse-linuxtools
  - eclipse-manpage
  - eclipse-mpc
  - eclipse-pydev
  - eclipse-rpm-editor

- name: Install additional eclipse plugins
  shell: |
    eclipse -nosplash -application org.eclipse.equinox.p2.director \
      -repository {{ item.repo }} -installIU {{ item.plugin }}
  ignore_errors: yes
  with_items:
  - { plugin: 'de.vonloesch.pdf4eclipse.feature.group',                         repo: 'http://texlipse.sourceforge.net/' }
  - { plugin: 'net.sourceforge.texlipse.feature.group',                         repo: 'http://texlipse.sourceforge.net/' }
  - { plugin: 'org.apache.directory.studio.ldapbrowser.feature.feature.group',  repo: 'http://directory.apache.org/studio/update' }
  - { plugin: 'org.apache.directory.studio.ldifeditor.feature.feature.group',   repo: 'http://directory.apache.org/studio/update' }
  - { plugin: 'org.apache.directory.studio.schemaeditor.feature.feature.group', repo: 'http://directory.apache.org/studio/update' }
  - { plugin: 'org.dadacoalition.yedit.feature.feature.group',                  repo: 'http://dadacoalition.org/yedit' }
  - { plugin: 'org.eclipse.wst.common_ui.feature.feature.group',                repo: 'http://download.eclipse.org/releases/{{ ECLIPSE_RELEASE }}' }
  - { plugin: 'org.eclipse.wst.xml_ui.feature.feature.group',                   repo: 'http://download.eclipse.org/releases/{{ ECLIPSE_RELEASE }}' }
  - { plugin: 'org.psem2m.eclipse.rest.editor.feature.group',                   repo: 'http://resteditor.sourceforge.net/eclipse' }

- name: Create .project files
  template:
    src: eclipse_project
    dest: '{{ WORKSPACE }}/{{ item.path }}/.project'
    force: no
  with_items:
  - { name: 'authconfig',       path: 'authconfig',       cproject: False }
  - { name: 'authselect',       path: 'authselect',       cproject: True }
  - { name: 'my-scripts',       path: 'my-scripts',       cproject: False }
  - { name: 'talloc',           path: 'samba/lib/talloc', cproject: True }
  - { name: 'tevent',           path: 'samba/lib/tevent', cproject: True }
  - { name: 'ldb',              path: 'samba/lib/ldb',    cproject: True }
  - { name: 'leapp-repository', path: 'leapp-repository', cproject: False }
  - { name: 'sssd',             path: 'sssd',             cproject: True }
  - { name: 'sssd-dev-utils',   path: 'sssd-dev-utils',   cproject: False }
  - { name: 'sssd_docs',        path: 'sssd_docs',        cproject: False }
  - { name: 'sssd-ci',          path: 'sssd-ci',          cproject: False }
  - { name: 'sssd-test-suite',  path: 'sssd-test-suite',  cproject: False }
  - { name: 'sudo',             path: 'sudo',             cproject: True }
  - { name: 'test-area',        path: 'test-area',        cproject: True }
  - { name: 'packages',         path: 'packages',         cproject: False }
  - { name: 'virtual-machines', path: 'virtual-machines', cproject: False }

- name: Create .cproject files for Makefile projects
  template:
    src: eclipse_cproject_makefile
    dest: '{{ WORKSPACE }}/{{ item.path }}/.cproject'
    force: no
  with_items:
  - { name: 'authselect',      path: 'authselect',       settings: '{{ project_authselect }}' }
  - { name: 'talloc',          path: 'samba/lib/talloc', settings: '{{ project_talloc }}' }
  - { name: 'tevent',          path: 'samba/lib/tevent', settings: '{{ project_tevent }}' }
  - { name: 'ldb',             path: 'samba/lib/ldb',    settings: '{{ project_ldb }}' }
  - { name: 'sssd',            path: 'sssd',             settings: '{{ project_sssd }}' }
  - { name: 'sudo',            path: 'sudo',             settings: '{{ project_sudo }}' }

- name: Create .cproject files for projects build by Eclipse
  template:
    src: eclipse_cproject_build
    dest: '{{ WORKSPACE }}/{{ item.path }}/.cproject'
    force: no
  with_items:
  - { name: 'test-area',       path: 'test-area',        settings: '{{ project_test_area }}' }

- name: Check if Eclipse workspace already exists
  stat:
    path: '{{ WORKSPACE }}/.metadata'
  register: workspace

- name: Create workspace metadata
  synchronize:
    src: 'workspace/.metadata'
    dest: '{{ WORKSPACE }}'
  when: not workspace.stat.exists
